name: Update Image
env:
  AZURE_WEBAPP_NAME: "ibm-webapp"
  IMAGE_REGISTRY: "ghcr.io"
  RESROUCES_PREFIX: "IBM-PROJECT"

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Building and pushing container image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my-app
    outputs:
      image_name: ${{ steps.image_name.outputs.image_name }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.IBM_REPO_TOKEN }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Get tag from VERSION file
        run: echo "IMAGE_TAG=$(cat VERSION)" >>${GITHUB_ENV}

      - name: Create image name
        run: echo "IMAGE_NAME=${{ env.REPO }}/${{ env.AZURE_WEBAPP_NAME }}:${{ env.IMAGE_TAG }}" >>${GITHUB_ENV}

      - name: Output image name 
        id: image_name
        run: echo "image_name=${{ env.IMAGE_NAME }}" >> $GITHUB_OUTPUT    

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./my-app
          build-args: |
            IMAGE_TAG=${{ env.IMAGE_TAG }}
          tags: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          file: ./my-app/Dockerfile

  deploy:
    name: Deploying to Azure Web App
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.RESROUCES_PREFIX }}-WEBAPP
          images: ${{ env.IMAGE_REGISTRY }}/${{ needs.build.outputs.image_name }}
