name: Destroying Infrastructure
env:
  RESROUCES_PREFIX: "IBM-PROJECT"

on:
  workflow_dispatch:
    inputs:
      DESTROY_REMOTE_STATE: 
        description: 'Do you also want to destroy the remote state?'
        required: true
        default: 'false'

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
    
    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Destroy Infrastructure
        run: |
          az group delete --name ${{ env.RESROUCES_PREFIX }}-RG --yes --no-wait
          
      - name: Destroying remote state
        if: ${{ github.event.inputs.DESTROY_REMOTE_STATE == 'true' }}
        run: |
          az group delete --name ${{env.RESROUCES_PREFIX}}-RG-STATE --yes --no-wait